### PR TITLE
Parse Cisco ASA-5-304001

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by purbon** [comment]
Good morning @sathieu , thanks a lot for your contribution. In order to move forward with your contribution you will need to sign the CLA, more info at -> https://www.elastic.co/contributor-agreement

On the other side, we just added the option to test the grok patterns we've in here, adding test to validate your changes it will be cool to merge this in too. You can take inspiration to write the test from (https://github.com/logstash-plugins/logstash-patterns-core/blob/master/spec/patterns/syslog_spec.rb), don't heasitate to ask any question you might have, we'll be happy to provide help.

**Comment by sathieu** [comment]
@purbon This patch is under public domain. You can merge it without me signing the CLA (I won't sign it).

**Comment by purbon** [comment]
Good morning @sathieu, 
    I understand your concerns and why you might not be willing to sign the CLA, however in the benefit of everyone involved in the community we believe this process is the most fair, as for example many other communities does, like the apache one, the eclipse project, etc.

A good read on the topic is: https://www.chef.io/blog/2009/08/11/why-we-chose-the-apache-license/

Where they exactly say this:

> The requirement for the CLA is for everyone’s protection – end users can be sure that the code is free from legal entanglements, developers can be certain their rights are explicit, and companies canbe assured that by using the software they don’t expose themselves to any additional legal risk.

I would be more than happy to bring this improvement in, in case you change your mind let me know!

**Comment by purbon** [comment]
I'm sorry you did not decide to sign the CLA, I would close this PR for now, more than welcome to reopen this if you change your mind.

Thanks a lot for your time man!

- purbon

**Pull request closed without merging**
