### PR TITLE
add a pattern for rails 3

### PR DESCRIPTION
**Pull request by igalic**
This is the rails pattern we use in our configuration.
It's based off @mudge's [gist](https://gist.github.com/mudge/5047696) and @ese's improvements.

### CODE REVIEW

**Comment by igalic** [comment]
re tests (since most of the other pull requests here are labeled with missing them)

```
igalic@levix ~/src/elastic/logstash-patterns-core (git)-[patch-1] % bundle
Your Gemfile lists the gem logstash-filter-grok (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Could not find gem 'logstash-devutils (>= 0) ruby' in any of the gem sources listed in your Gemfile or available on this machine.
```

**Comment by ph** [comment]
@igalic You have to run JRuby to be able to run the tests, if you are using rbenv or rvm it is a simple install.

**Comment by igalic** [comment]
@ph thanks for the pointer.
did that just now, and can run tests just fine!
yay! partial success. now i have to figure out how to spec test multi-line patterns.
(as soon as i do, i should provide a patch for the java patterns as well ;)

*****

@ese please note that we have largely no influence on these applications (gitlab, redmine)

**Comment by igalic** [comment]
@ph added two tests

**Comment by purbon** [comment]
LGTM

**Pull request closed without merging**
