### PR TITLE
Update month for german month names + add Catalina and Tomcat pattern

### PR DESCRIPTION
**Pull request by cniweb**
see:
https://github.com/logstash-plugins/logstash-patterns-core/issues/34

### CODE REVIEW

**Comment by cniweb** [comment]
@purbon I forgot to update the new branch to the current master!
I hope it´s OK?

**Comment by purbon** [comment]
Hi,
  I see something strange here, do you want to do a PR for the tomcat + the german names ? or just for the german names ? was this a mistake? 

When I said in #26 that you should rebase againts master I was meening to sync with the logstash-patterns-core master, this makes the merge proccess simplier. Actually the PR now says it containts conflicts that need to be resolved.

I still see you didn't sign the cla, is this right?

**Comment by cniweb** [comment]
OK, i do all in one PR.

**Comment by cniweb** [comment]
@purbon OK, now?

**Comment by purbon** [comment]
@cniweb The is still one small step missing, you need to sign the CLA https://www.elastic.co/contributor-agreement let me know when done :-) thanks!!

**Comment by cniweb** [comment]
OK, I have confirm the CLA! :-)

**Comment by cniweb** [comment]
@purbon When will a new version released?

**Comment by purbon** [comment]
Merging this manually.

**Comment by purbon** [comment]
This has been merge into master. Thanks for your time and sharing.

**Pull request closed without merging**
