### PR TITLE
add some missing Cisco ASA firewall system log patterns

### PR DESCRIPTION
**Pull request by frennkie**
Add some missing Cicso ASA firewall system log patterns which
can be found in the according documentation on cisco.com.

### CODE REVIEW

**Comment by frennkie** [comment]
I was working with a few log files from a lab setup and noticed that theses messages type are not parsed. It would be nice if you could include them.

**Comment by purbon** [comment]
Thanks for your PR @frennkie! before we move on with it, can you please add some test. You can take inspiration from what it was done for the MONGODB logs at https://github.com/logstash-plugins/logstash-patterns-core/pull/29/files

/cheers

**Comment by purbon** [comment]
You will also need to sign the CLA, more information at https://www.elastic.co/contributor-agreement

**Comment by frennkie** [comment]
I signed the CLA and also added a first test. Can you check whether this is going in the right direction?

**Comment by purbon** [comment]
@frennkie that is perfect, you should add different log lines (if applied) and check for the fields expected to be extracted. This is looking very good! thanks!

- purbon

**Comment by frennkie** [comment]
Dear @purbon, good to know that I'm heading in the right direction.
I'm not in the office for the next two weeks so I don't have access to the log files for extracting some real life messages for other tests. I'll work on that when I'm back at work.
In the meanwhile I added a test for message ID 106100 which is referenced in Pull Request #51.
As that is a bug you may want to accept this PR or at least the part dealing with testing the bug fix that @mcnewton provided.

Thanks,
kind Reards
frennkie

**Comment by purbon** [comment]
Thanks for the intel @frennkie and I will review #51. We can take this back as soon as you get to the office back.

**Comment by purbon** [comment]
@frennkie @mcnewton will need to sign the CLA before we can move on on merging his PR.

**Comment by mcnewton** [comment]
Just noticed this... I'll have a look.

**Comment by purbon** [comment]
Just merged this manually, including a version bump and a changelog.md update. Thanks for your time and contributions :+1:  Feel free to ping here again for any other kind of issue with the patterns.

**Pull request closed without merging**
