### PR TITLE
Update CloudFront Pattern for x_edge_location

### PR DESCRIPTION
**Pull request by prayashm**
CloudFront edge locations can have hyphens in them.

### CODE REVIEW

**Comment by andrewvc** [comment]
`DATA` should be used sparingly since its greedy.

You probably want `NOTSPACE`

**Comment by prayashm** [comment]
Yep, that's right

**Comment by gregsymons** [comment]
Any idea when this might get merged in?

**Comment by gregsymons** [comment]
After looking more closely at some of the logs that _were_ getting parsed with the existing pattern, some of the fields were getting parsed out incorrectly. I think all the places where this pattern is using `GREEDYDATA` should probably be `NOTSPACE`, too. Here's a pattern that I've tested (granted, only on one line 😄 ) that gets everything (including some new fields at the end of the log records):

```
(?<timestamp>%{YEAR}-%{MONTHNUM}-%{MONTHDAY}\t%{TIME})\t%{NOTSPACE:x_edge_location}\t(?:%{NUMBER:sc_bytes:int}|-)\t%{IPORHOST:clientip}\t%{WORD:cs_method}\t%{HOSTNAME:cs_host}\t%{NOTSPACE:cs_uri_stem}\t%{NUMBER:sc_status:int}\t%{NOTSPACE:referrer}\t%{NOTSPACE:agent}\t%{NOTSPACE:cs_uri_query}\t%{NOTSPACE:cookies}\t%{WORD:x_edge_result_type}\t%{NOTSPACE:x_edge_request_id}\t%{HOSTNAME:x_host_header}\t%{URIPROTO:cs_protocol}\t%{INT:cs_bytes:int}\t%{NOTSPACE:time_taken:float}\t%{NOTSPACE:x_forwarded_for}\t%{NOTSPACE:ssl_protocol}\t%{NOTSPACE:ssl_cipher}\t%{NOTSPACE:x_edge_response_result_type}\t%{NOTSPACE:cs-protocol-version}\t%{NOTSPACE:fle-status}\t%{NOTSPACE:fle-encrypted-fields}
```
It's basically a global replace of `GREEDYDATA` with `NOTSPACE` and adds the `cs-protocol-version`, `fle-status`, and `fle-encrypted-fields` fields at the end. Since I haven't seen the `fle-status` or `fle-encrypted-fields` in my data, I'm not 100% sure `NOTSPACE` is the best match.

**Comment by nokiomanz** [comment]
Hi, 

I just found out this morning that there was a pattern for cloudfront named CLOUDFRONT_ACCESS_LOG. But the pattern won't work with edge locations that has hyphens.

I have been using this pattern for the past year with 0 _grokparsefailure
`(?<timestamp>%{YEAR}-%{MONTHNUM}-%{MONTHDAY}\t%{TIME})\t%{NOTSPACE:x_edge_location}\t(?:%{NUMBER:sc_bytes:int}|-)\t%{IPORHOST:clientip}\t%{WORD:cs_method}\t%{HOSTNAME:cs_host}\t%{NOTSPACE:cs_uri_stem}\t%{NUMBER:sc_status:int}\t%{NOTSPACE:referrer}\t%{NOTSPACE:agent}\t%{NOTSPACE:cs_uri_query}\t%{NOTSPACE:cookies}\t%{WORD:x_edge_result_type}\t%{NOTSPACE:x_edge_request_id}\t%{HOSTNAME:x_host_header}\t%{URIPROTO:cs_protocol}\t%{INT:cs_bytes:int}\t%{NOTSPACE:time_taken:float}\t%{NOTSPACE:x_forwarded_for}\t%{NOTSPACE:ssl_protocol}\t%{NOTSPACE:ssl_cipher}\t%{NOTSPACE:x_edge_response_result_type}`

Adding the last 3 field as per gregsymons is indeed a nice addition.

**Pull request closed without merging**
