### PR TITLE
Added support for MongoDB version 3 kind of logs

### LINKED ISSUE #28: Mongo 3 log changes
Hi!
I was looking for mongodb 3 log patterns and I end up here just to notice that your mongo patterns are outdated for the version 3 of the database

And example:
You say:

MONGO_LOG %{SYSLOGTIMESTAMP:timestamp} \[%{WORD:component}\] %{GREEDYDATA:message}

But the new version turns out to be:

%{TIMESTAMP_ISO8601:timestamp} %{WORD:severity} %{WORD:component}  \[%{WORD:context}\] %{GREEDYDATA:message}

See official documentation on the matter: http://docs.mongodb.org/manual/reference/log-messages/

I'm looking for the rest of the patterns but this one groks just fine in my tests
As soon as I found any other will post here if you are ok with it

Thanks

### PR DESCRIPTION
**Pull request by purbon**
Fixes #28 

MongoDB v3 add a new format for logs as stated in http://docs.mongodb.org/manual/reference/log-messages/

### CODE REVIEW

**Comment by purbon** [comment]
@wiibaa @Garito @suyograo can you review and take a look to this change ?

**Comment by wiibaa** [comment]
I'm not using mongo3 myself, but from the doc and some real world example found in  there http://dba.stackexchange.com/questions/94421/mongo-3-intermitted-crashes 

* WORD pattern is not catching the unnamed component `-` 
* in real world example it seems that the logs are formatted with multiple spaces, so current pattern is too fragile

Therefore I would be in favor of defining explicitly enumeration for both MONGO_SEVERITY and MONGO_COMPONENT and use %{SPACE} in between

HTH

**Comment by wiibaa** [comment]
oh forgot to mention that the test look awesome

**Comment by Garito** [comment]
I'm agree with @wiibaa about the space thing
Apart of that seems good to me, thanks

**Comment by Garito** [comment]
I forgot to mention something relevant here:
Mongo3 is sending a message (I don't recall if was at stop or restart) that don't follow this pattern so groks raises a grokparsefailure

This is my filter about that:
if [type] == "mongo" {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{WORD:severity} %{WORD:component}  \[%{WORD:context}\] %{GREEDYDATA:the_message}" }
    }  
    
    if "_grokparsefailure" in [tags] {
      grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{WORD:severity} %{WORD:component}  %{GREEDYDATA:the_message}" }
      }
      
      mutate {
        remove_field => [ "tags" ]
      }
    }
    
    date {
      match => [ "timestamp", "ISO8601" ]
    }

Perhaps this is useful for you or something

I have a pattern for Elasticsearch but I can't test it in production so don't really know if it is correct and covers the 100% of the cases without any parse failure

Perhaps here is not the good place to put it but I can make a new issue with the pattern if you need 

if [type] == "ElasticLog" {
    grok {
      match => { "message" => "\[%{TIMESTAMP_ISO8601:timestamp}\]\[%{DATA:severity}%{SPACE}\]\[%{DATA:source}%{SPACE}\] \[%{DATA:node}\] %{GREEDYDATA:the_message}" }
    }
    
    date {
      match => [ "timestamp", "YYYY-MM-dd HH:mm:ss,SSS" ]
    }
  }

Thanks

**Comment by wiibaa** [comment]
@purbon could not resist toying with the new test syntax so created https://github.com/purbon/logstash-patterns-core/pull/1/files
Also I made a quick mongo install to check @Garito warning about optional context that is indeed omited in a few messages like on shutdown
````
2015-04-23T07:00:13.864+0200 I CONTROL  Ctrl-C signal
````
or at windows startup
````
2015-04-23T06:57:28.049+0200 I CONTROL  Hotfix KB2731284 or later update is not installed, will zero-out data files
````
also found out that context should be more than a simple word like in 
````
2015-04-23T07:00:13.970+0200 I JOURNAL  [journal writer] Journal writer thread stopped
````
I hope this would be enough for this new pattern to make a shining start :D

**Comment by Garito** [comment]
Agree with the context with more than a word, thanks for pointing it out. The truth is that since I haven't finish the infrastructure work (dealing with this issue not only here but in the elasticsearch official image and so on -> next step Nginx) I don't really test the pattern far away from the startup/shutdown process but I was looking for the official documentation for this pattern (the one that doesn't tell us explicit that the context could be bigger than only one word)

So agree with the correction

**Comment by Garito** [comment]
Perhaps instead of:
MONGO3_LOG %{TIMESTAMP_ISO8601:timestamp} %{WORD:severity} %{WORD:component} \[%{WORD:context}\] %{GREEDYDATA:message}
will be:
MONGO3_LOG %{TIMESTAMP_ISO8601:timestamp} %{WORD:severity} %{WORD:component} \[%{DATA:context}\] %{GREEDYDATA:message}
isn't it?

I would like to point out that the last log line @wiibaa put is those logs lines I told you that doesn't have any context (in my filter I check if there is a _grokparsefailure to check it an fall back to the more general pattern without the context field

**Comment by wiibaa** [comment]
@Garito :+1:  I proposed the same change from WORD to DATA in the pull request on this pull request, this is not directly visible here but the final patterns (with an optional context) would be
````
MONGO3_SEVERITY F|E|W|I|D
MONGO3_COMPONENT ACCESS|COMMAND|CONTROL|GEO|INDEX|NETWORK|QUERY|REPL|SHARDING|STORAGE|JOURNAL|WRITE|-
MONGO3_LOG %{TIMESTAMP_ISO8601:timestamp} %{MONGO3_SEVERITY:severity} %{MONGO3_COMPONENT:component}%{SPACE}(?:\[%{DATA:context}\])? %{GREEDYDATA:message}
````

**Comment by Garito** [comment]
With this pattern I could simplify my filter but I'm not fully sure that severity and component ors are a good idea (I think of what happen if they decide to add a new one)
As I see this logs, they will end up in a terms field in elasticsearch so don't really care how much they are...

**Comment by wiibaa** [comment]
That was just to have a simple base for getting started and writting testcases, switching to a more generic approach let the test case happy. so final decision is left to @purbon héhé
````
MONGO3_SEVERITY \w
MONGO3_COMPONENT %{WORD}|-
MONGO3_LOG %{TIMESTAMP_ISO8601:timestamp} %{MONGO3_SEVERITY:severity} %{MONGO3_COMPONENT:component}%{SPACE}(?:\[%{DATA:context}\])? %{GREEDYDATA:message}
````

**Comment by purbon** [comment]
This looks awesome, I like the way we discussed and shared knowledge here!! 

I'm today at OSDC to talk about Logstash (https://www.netways.de/index.php?id=2567&L=1), but as soon as I have time to review this as it deserved i'm back with this.

**Comment by Garito** [comment]
@purbon tell me if you wanna that i move the elasticsearch pattern to the elasticsearch image project

**Comment by purbon** [comment]
Back in the trenches today, will start reviewing this.

**Comment by purbon** [comment]
@wiibaa really like it your cross PR move, well done man!

**Comment by purbon** [comment]
@Garito speaking about the Elasticsearch pattern, this is a very cool do you mind doing your first PR to this repo with this new pattern. Basically to do it you need to:

* Create a new file in the patterns directory.
* Add test as for example in this PR.

easy peace and obviously I'm here to help!

Looking forward to it.

**Comment by purbon** [comment]
@wiibaa @Garito if you have nothing else against, I'm going to merge this after lunch. 

@wiibaa I squashed the commits in order to have an smaller PR, i hope this is still ok for you :-), otherwise let me know

**Comment by wiibaa** [comment]
squashing is good for readability ++

**Pull request closed without merging**
