### PR TITLE
Modify TZ to allow AEST

### PR DESCRIPTION
**Pull request by mxhob1**
Updated the TZ regex to allow detection of Australian Eastern Standard Time (UTC+10)

### CODE REVIEW

**Comment by stefan-o** [comment]
+1

**Comment by ph** [comment]
@mxhob1 Would you mind doing step 2 of the contributing guide? https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

Also should we keep `PMCE` ?

**Comment by mxhob1** [comment]
@ph I had signed the CLA after posting the PR, can you recheck?

The updated regex will cater for the previous criteria

**Comment by markwalkom** [comment]
LGTM (for whatever it is worth ;)

**Comment by ph** [comment]
@mxhob1 did you use the same email when signing up that we see the patch file ? 
https://patch-diff.githubusercontent.com/raw/logstash-plugins/logstash-patterns-core/pull/148.patch

**Comment by mxhob1** [comment]
Ah, that is an old email address. It was signed under michael@hobl.com.au with my Github username.

**Comment by karmi** [comment]
Hi Michael, can you please add both of the e-mails to your Github profile? This should work on our side, to properly match you against Github username. If you don't have access to the old e-mail anymore, would it be possible to just commit it with the new one, and force push?

```bash
git commit --verbose --author="John Smith <john@smith.com>" --amend
git push --force
```

**Comment by karmi** [comment]
Hi @mxhob1, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-patterns-core/pull/148.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by mxhob1** [comment]
@karmi: I have re-committed with the new email as I don't have access to the old one and all checks seem to have passed this time

**Pull request closed without merging**
