### PR TITLE
add pattern for S3 and ELB

### PR DESCRIPTION
**Pull request by jsvd**
migrated from https://github.com/elasticsearch/logstash/pull/1327
tests are failing: 
```
  1) LogStash::Patterns::Core s3 access log format "79a5 mybucket [06/Feb/2014:00:00:38 +0000] 192.0.2...." when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected nil, got 0
     # ./spec/patterns/core_spec.rb:31:in `(root)'

  2) LogStash::Patterns::Core s3 access log format "79a5 mybucket [12/May/2014:07:54:01 +0000] 10.0.1.2..." when processed
     Failure/Error: Unable to find matching line from backtrace
     Insist::Failure:
       Expected nil, got 0
     # ./spec/patterns/core_spec.rb:54:in `(root)'
```

### CODE REVIEW

**Comment by DanielRedOak** [comment]
I would prefer that the field names align with the field names Amazon outlines: http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/access-log-collection.html  Also, how can we handle the case where it is trying (successfully) to coerce nil to an int and returning 0?  Not super familiar with the grok implementation itself, so it might just be ignorance

**Comment by DanielRedOak** [comment]
As a matter of opinion I submitted those changes along with updates to allow these patterns to work with TCP ELBs and removed coercion on the optional int fields.  If there is a better way to handle the coercion besides removing it, let me know!

**Comment by vanga** [comment]
ELB pattern doesn't work with logs like these 
```
2015-04-10T08:11:09.865823Z us-west-1-production-media 49.150.87.133:55128 - -1 -1 -1 408 0 1294336 0 "PUT https://media.xxxyyyzzz.com:443/videos/F4_M-T4X0MM6Hvy1PFHesw HTTP/1.1"
```

**Comment by vanga** [comment]
`(?:(?:%{IP:backendip}):(?:%{INT:backendport:int})|-)`

This particular change is sifficient to parse the above log.

One more thing, I dont see the `backendport` field in the output for some reason (prior to my change also).

**Comment by andrewvc** [comment]
Trying to run the specs here I'm getting errors. Any ideas @jordansissel ?

```
LogStash::PluginLoadingError: Couldn't find any filter plugin named 'grok'. Are you sure this is correct? Trying to load the grok filter plugin resulted in this error: uninitialized constant LogStash::Environment::LOGSTASH_HOME
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/logstash-core-1.5.2.2-java/lib/logstash/plugin.rb:142:in `lookup'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/logstash-core-1.5.2.2-java/lib/logstash/pipeline.rb:290:in `plugin'
(eval):7:in `initialize'
org/jruby/RubyKernel.java:1111:in `eval'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/logstash-core-1.5.2.2-java/lib/logstash/pipeline.rb:30:in `initialize'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/logstash-devutils-0.0.15-java/lib/logstash/devutils/rspec/logstash_helpers.rb:34:in `pipeline'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/memoized_helpers.rb:242:in `pipeline'
org/jruby/RubyHash.java:1181:in `fetch'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/memoized_helpers.rb:242:in `pipeline'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/logstash-devutils-0.0.15-java/lib/logstash/devutils/rspec/logstash_helpers.rb:45:in `results'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/memoized_helpers.rb:242:in `results'
org/jruby/RubyHash.java:1181:in `fetch'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/memoized_helpers.rb:242:in `results'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/logstash-devutils-0.0.15-java/lib/logstash/devutils/rspec/logstash_helpers.rb:58:in `subject'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/memoized_helpers.rb:242:in `subject'
org/jruby/RubyHash.java:1181:in `fetch'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/memoized_helpers.rb:242:in `subject'
./spec/patterns/core_spec.rb:16:in `(root)'
org/jruby/RubyProc.java:271:in `call'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/insist-1.0.0/lib/insist.rb:47:in `value'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/insist-1.0.0/lib/insist/nil.rb:5:in `nil?'
./spec/patterns/core_spec.rb:16:in `(root)'
org/jruby/RubyBasicObject.java:1566:in `instance_exec'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:152:in `run'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:329:in `with_around_example_hooks'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:149:in `run'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:490:in `run_examples'
org/jruby/RubyArray.java:2412:in `map'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:486:in `run_examples'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:453:in `run'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `run'
org/jruby/RubyArray.java:2412:in `map'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `run'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `run'
org/jruby/RubyArray.java:2412:in `map'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `run'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `run_specs'
org/jruby/RubyArray.java:2412:in `map'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `run_specs'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/reporter.rb:53:in `report'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:107:in `run_specs'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:85:in `run'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/lib/ruby/gems/shared/gems/rspec-core-3.1.7/exe/rspec:4:in `(root)'
org/jruby/RubyKernel.java:1091:in `load'
/Users/andrewvc/.rbenv/versions/jruby-1.7.20/bin/rspec:1:in `(root)'
org/jruby/RubyKernel.java:1091:in `load'
-e:1:in `(root)'
```

**Comment by purbon** [comment]
@andrewvc we/I changed the way to write specs here, this might be the reason. I will take care of updating this PR to the new syntax and get this in.

**Comment by purbon** [comment]
Bumped, add test, and merged this changes in https://github.com/logstash-plugins/logstash-patterns-core/pull/70

**Pull request closed without merging**
