### PR TITLE
Remove duplicate patterns JAVACLASS and JAVAFILE

### PR DESCRIPTION
**Pull request by jsvd**

### CODE REVIEW

**Comment by jsvd** [comment]
> maybe some comment in the commit/changelog as to the reasons why those definitions were removed

@robbavey that was my goal with the tests, both test an example of the pattern that only works for the remaining one.

**Comment by robbavey** [comment]
@jsvd Ah cool, ok LGTM then

**Comment by jakelandis** [comment]
@jsvd - thanks for the heads up, issue logged for the ingest node: https://github.com/elastic/elasticsearch/issues/35699

**Pull request merged**
