### PR TITLE
added email address as a potential format for the HTTPD "auth" field.

### PR DESCRIPTION
**Pull request by philhagen**
Addresses https://github.com/logstash-plugins/logstash-patterns-core/issues/3

### CODE REVIEW

**Comment by purbon** [comment]
Thanks a lot for your contribution @philhagen , in order to move forward with your PR is going to be necessary to sign the CLA agreement, you can find more information at https://www.elastic.co/contributor-agreement.

On the other side, it would be super nice if you can add test for this change. We try to enforce that all PR introduce some kind of testing, so we're able to increase the overall quality. Don't hesitate to ask any question regarding you might have, more than looking forward to help.

**Comment by purbon** [comment]
Closing this for now as the CLA request got stale without an answer for long time, if you change your mind and sign the CLA we would be more than welcome to get this in.

Thanks a lot for your contribution.

**Comment by philhagen** [comment]
I just signed and submitted the CLA the other day - did it not come through?

-Phil

**Comment by purbon** [comment]
This got merged https://github.com/logstash-plugins/logstash-patterns-core/commit/767052713f5e6114bfc1aa9cdd79bc2976b71bd4

**Pull request closed without merging**
