### PR TITLE
Update bro

### PR DESCRIPTION
**Pull request by ajmurphy**
Added content to capture the "oric_cc", "resp_cc", and "sensorname" fields.

Also I noticed that I was having entries fail to parse when the duration, orig_bytes, or resp_bytes were not present, so by changing the definition in the GROK pattern from {NUMBER} to {NOTSPACE} they will still parse correctly.

This is working on my Bro 2.4 version perfectly now.

### CODE REVIEW

**Comment by purbon** [comment]
please jenkins, test this.

**Comment by purbon** [comment]
Hi @ajmurphy, thanks a lot for your contribution. Before we can moving forward with this PR, we'll need you to sign the CLA, you can find more about it at https://www.elastic.co/contributor-agreement thanks a lot, looking forward to it.

**Comment by ajmurphy** [comment]
CLA Signed.

**Comment by ajmurphy** [comment]
@purbon do I need to resubmit this PR now that I've signed the CLA?

**Comment by purbon** [comment]
@ajmurphy no, cool you signed!

**Comment by kares** [comment]
we've recently updated BRO patterns to handle newer formats along side with making captures ECS compliant.
there's a new set of `ZEEK_xxx` patterns, the [CONN pattern](https://github.com/logstash-plugins/logstash-patterns-core/pull/286/files#diff-5a3b6c47c52e9c8de9db9fd064b2ac5609f569a0031957a9fed557d7fe34326bR14) in particular handles `source.mac` and `destination.mac` at the end. 
closing this PR as it would need to be revisited (new captures should be optional due compatibility) and is also missing tests.

**Pull request closed without merging**
