### PR TITLE
Adding maven version to the list of default Grok patterns

### PR DESCRIPTION
**Pull request by carlphilipp**

### CODE REVIEW

**Comment by carlphilipp** [comment]
I just signed the CLA

**Comment by carlphilipp** [comment]
When I run the test I have this error:

bundle exec rspec

Using Accessor#strict_set for specs
NoMethodError: undefined method `pattern_path' for LogStash::Environment:Module
             Grok at /Users/charmant/.rvm/gems/jruby-1.7.19/gems/logstash-filter-grok-2.0.3/lib/logstash/filters/grok.rb:222
           (root) at /Users/charmant/.rvm/gems/jruby-1.7.19/gems/logstash-filter-grok-2.0.3/lib/logstash/filters/grok.rb:139
          require at org/jruby/RubyKernel.java:1071
          require at /Users/charmant/.rvm/gems/jruby-1.7.19/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /Users/charmant/git/logstash-patterns-core/spec/spec_helper.rb:1
          require at org/jruby/RubyKernel.java:1071
           (root) at /Users/charmant/git/logstash-patterns-core/spec/spec_helper.rb:11
             load at org/jruby/RubyKernel.java:1087
           (root) at /Users/charmant/git/logstash-patterns-core/spec/patterns/core_spec.rb:1
             each at org/jruby/RubyArray.java:1613
           (root) at /Users/charmant/git/logstash-patterns-core/spec/patterns/core_spec.rb:2
           (root) at /Users/charmant/.rvm/gems/jruby-1.7.19/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1
  load_spec_files at /Users/charmant/.rvm/gems/jruby-1.7.19/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105
  load_spec_files at /Users/charmant/.rvm/gems/jruby-1.7.19/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105
            setup at /Users/charmant/.rvm/gems/jruby-1.7.19/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96
              run at /Users/charmant/.rvm/gems/jruby-1.7.19/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84
             load at org/jruby/RubyKernel.java:1087
              run at /Users/charmant/.rvm/gems/jruby-1.7.19/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69
             eval at org/jruby/RubyKernel.java:1107
           (root) at /Users/charmant/.rvm/gems/jruby-1.7.19/bin/jruby_executable_hooks:15

**Comment by jsvd** [comment]
can you move this into a separate file called maven and add a test to it? there are many examples already for other patterns

**Comment by karmi** [comment]
Hi @carlphilipp, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-patterns-core/pull/130.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by carlphilipp** [comment]
Hello @karmi, I updated my account with my other email, you should be able to verify it.
I also created a new file for maven, and some tests for it. Let me know if it's good enough, I'm not super familiar with Ruby

**Comment by jsvd** [comment]
LGTM

**Pull request merged**
