### PR TITLE
Update firewalls with more Cisco ASA patterns

### PR DESCRIPTION
**Pull request by dthvt**

### CODE REVIEW

**Comment by purbon** [comment]
Thanks a lot @dthvt for your contribution, nowadays we try to enforce having test for this patterns, you can take a look inside the specs directory of this project.

Do you mind adding test for the new patterns you added? this would help moving forward merging this PR.

Thanks!

- purbon

**Comment by dthvt** [comment]
@purbon I can certainly appreciate the value of having tests, so I respect your request.  However, I don't foresee having the time to develop the test myself in the near future.  I developed the patterns for work, but I can't bill time for submitting upstream patches, and summer is my busiest time personally.  I will leave it on my todo list, though, for whenever things slow down.

Cheers,

Daniel

**Comment by purbon** [comment]
@dthvt I can write the test for you, but I will need some sample logs :-) ... can you provide me with that?+

Thanks man!

**Comment by purbon** [comment]
Hi @dthvt, 
     to move this a bit forward we would also need you to sign the CLA, more info at -> https://www.elastic.co/contributor-agreement 

Did you had any chance to get some example log lines ? then I'm more than welcome to help out with test :smile: 

/cheers

**Pull request closed without merging**
