### PR TITLE
Add Catalina and Tomcat pattern

### PR DESCRIPTION
**Pull request by cniweb**
Add log patterns for Catalina and Tomcat log files.

### CODE REVIEW

**Comment by purbon** [comment]
Good morning, thank you for your contribution. Today, we just added a nice way to test patterns before they get in, you can check an example rspec code in https://github.com/logstash-plugins/logstash-patterns-core/blob/master/spec/patterns/core_spec.rb#L23. 

Can you add a few test for this pattern? This would be very nice of you. Then we can merge as we're going to be sure the pattern works as expected always.

The test examples are intended to be simple, but if you've questions just let me know and I will guide you.

**Comment by cniweb** [comment]
@purbon OK i add a TOMCATLOG spec

**Comment by purbon** [comment]
Awesome!

/cheers

On Thursday, May 7, 2015, Christian Häussler <notifications@github.com>
wrote:

> @purbon <https://github.com/purbon> OK i add a TOMCATLOG spec
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/logstash-plugins/logstash-patterns-core/pull/26#issuecomment-99747062>
> .
>


-- 
Pere Urbon-Bayes
Software Engineer
https://www.elastic.co
https://twitter.com/purbon

**Comment by purbon** [comment]
Hi @cniweb, 
   If you like to, adding a few more test woudl be  nice, you can do somehthing like what is done for mongodb. Makes sense to you? 

But before we can merge, you will need to:

* Rebase this PR againts master.
* Squash your commits.
* Sign the CLA at https://www.elastic.co/contributor-agreement

After that I'm happy to get this into.

- purbon

**Comment by cniweb** [comment]
I Close this PR, do all in one PR.

**Pull request closed without merging**
